
/**
 * Constants for action types shared across views.
 */
export const sharedActionTypes = {
    SET_LEFT_MENU_EXPANDED:'SET_LEFT_MENU_EXPANDED',
    SET_RIGHT_SIDE_EXPANDED:'SET_RIGHT_SIDE_EXPANDED',
    SET_TAB_CHANGE:'SET_TAB_CHANGE',
    SET_LOGIN_USERNAME:'SET_LOGIN_USERNAME',
    SET_LOGIN_PASSWORD:'SET_LOGIN_PASSWORD',
    SET_LOGIN_REMEMBERME:'SET_LOGIN_REMEMBERME',
    SET_LOGIN_ERROR_MESSAGE:'SET_LOGIN_ERROR_MESSAGE',
    SET_LOGGED_IN:'SET_LOGGED_IN',
    SET_LOG_OUT:'SET_LOG_OUT',
    SET_LEFT_MENU_TOGGLE:'SET_LEFT_MENU_TOGGLE',
    SET_TOGGLE_PROFILE_MENU:'SET_TOGGLE_PROFILE_MENU',
    SET_DOCUMENT_CLICK:'SET_DOCUMENT_CLICK',
    SET_LEFT_MENU_SMALL_SCREEN_TOGGLED:"SET_LEFT_MENU_SMALL_SCREEN_TOGGLED",
    SET_RIGHT_MENU_SMALL_SCREEN_TOGGLED:'SET_RIGHT_MENU_SMALL_SCREEN_TOGGLED',
    SET_ROUTE_ON_MAP_OPENED:'SET_ROUTE_ON_MAP_OPENED'
};